"""CLI 能力清单（**由 ``gen_capability_spec.py`` 生成，请勿手改**）。

- 生成时间：2026-10-01 13:41:59
- CLI 版本：1.0.10
- 来源：``tencent-channel-cli schema -j`` + 逐命令 schema

人工维护的部分（分类、开关判定、提示词）在 ``capabilities.py`` 里。
升级 CLI 后重新生成：``python gen_capability_spec.py --schema <schema.json> --params <params.json>``
"""

from __future__ import annotations

from typing import Any

SPEC_CLI_VERSION = "1.0.10"
SPEC_GENERATED_AT = "2026-10-01 13:41:59"

CAPABILITIES: tuple[dict[str, Any], ...] = (

    {
        "name": "feed.get-guild-feeds",
        "domain": "feed",
        "action": "get-guild-feeds",
        "group": "read",
        "risk": "read",
        "summary": "获取腾讯频道主页帖子",
        "params": ["guild_id", "get_type", "count", "feed_attach_info"],
        "required": ["guild_id"],
    },
    {
        "name": "feed.get-channel-timeline-feeds",
        "domain": "feed",
        "action": "get-channel-timeline-feeds",
        "group": "read",
        "risk": "read",
        "summary": "获取版块帖子列表",
        "params": ["guild_id", "channel_id", "count", "feed_attach_info"],
        "required": ["guild_id", "channel_id"],
    },
    {
        "name": "feed.get-feed-detail",
        "domain": "feed",
        "action": "get-feed-detail",
        "group": "read",
        "risk": "read",
        "summary": "查看帖子详情",
        "params": ["feed_id", "guild_id", "channel_id"],
        "required": ["feed_id"],
    },
    {
        "name": "feed.get-feed-comments",
        "domain": "feed",
        "action": "get-feed-comments",
        "group": "read",
        "risk": "read",
        "summary": "查看帖子评论",
        "params": ["feed_id", "guild_id", "channel_id", "count", "rank_type", "reply_list_num", "attach_info"],
        "required": ["feed_id"],
    },
    {
        "name": "feed.search-guild-feeds",
        "domain": "feed",
        "action": "search-guild-feeds",
        "group": "read",
        "risk": "read",
        "summary": "搜索帖子",
        "params": ["guild_id", "query", "keyword", "next_page_cookie"],
        "required": ["guild_id"],
    },
    {
        "name": "feed.get-feed-share-url",
        "domain": "feed",
        "action": "get-feed-share-url",
        "group": "read",
        "risk": "read",
        "summary": "获取帖子分享短链",
        "params": ["feed_id", "guild_id", "channel_id"],
        "required": ["feed_id"],
    },
    {
        "name": "feed.get-notices",
        "domain": "feed",
        "action": "get-notices",
        "group": "read",
        "risk": "read",
        "summary": "查看互动消息",
        "params": ["page_num", "guild_id", "attach_info"],
        "required": [],
    },
    {
        "name": "feed.get-next-page-replies",
        "domain": "feed",
        "action": "get-next-page-replies",
        "group": "read",
        "risk": "read",
        "summary": "查看更多回复（评论回复分页）",
        "params": ["feed_id", "comment_id", "guild_id", "channel_id", "count", "attach_info"],
        "required": ["feed_id", "comment_id", "guild_id", "channel_id"],
    },
    {
        "name": "feed.publish-feed",
        "domain": "feed",
        "action": "publish-feed",
        "group": "write",
        "risk": "write",
        "summary": "发表帖子",
        "params": ["guild_id", "channel_id", "title", "content", "markdown_content", "content_file", "feed_type", "file_paths", "video_paths", "at_users", "urls", "topic_names"],
        "required": [],
    },
    {
        "name": "feed.del-feed",
        "domain": "feed",
        "action": "del-feed",
        "group": "write",
        "risk": "high-risk-write",
        "summary": "删除帖子",
        "params": ["feed_id", "guild_id", "channel_id", "create_time"],
        "required": ["feed_id", "guild_id", "channel_id", "create_time"],
    },
    {
        "name": "feed.do-comment",
        "domain": "feed",
        "action": "do-comment",
        "group": "write",
        "risk": "write",
        "summary": "发表/删除评论",
        "params": ["feed_id", "feed_create_time", "comment_type", "content", "image_path", "at_users", "urls", "comment_id", "comment_author_id", "guild_id", "channel_id", "ref"],
        "required": [],
    },
    {
        "name": "feed.do-reply",
        "domain": "feed",
        "action": "do-reply",
        "group": "write",
        "risk": "write",
        "summary": "发表/删除回复",
        "params": ["feed_id", "feed_author_id", "feed_create_time", "comment_id", "comment_author_id", "comment_create_time", "reply_type", "replier_id", "content", "image_path", "at_users", "urls", "target_reply_id", "target_user_id", "target_user_nick", "reply_id", "guild_id", "channel_id", "ref"],
        "required": [],
    },
    {
        "name": "feed.do-like",
        "domain": "feed",
        "action": "do-like",
        "group": "write",
        "risk": "write",
        "summary": "评论/回复点赞",
        "params": ["like_type", "feed_id", "comment_id", "guild_id", "channel_id", "feed_author_id", "feed_create_time", "comment_author_id", "reply_id", "reply_author_id", "comment_like_count", "reply_like_count"],
        "required": ["feed_id", "comment_id", "feed_author_id", "feed_create_time", "comment_author_id"],
    },
    {
        "name": "feed.do-feed-prefer",
        "domain": "feed",
        "action": "do-feed-prefer",
        "group": "write",
        "risk": "write",
        "summary": "帖子点赞/取消",
        "params": ["feed_id", "action", "guild_id", "channel_id"],
        "required": ["feed_id"],
    },
    {
        "name": "feed.alter-feed",
        "domain": "feed",
        "action": "alter-feed",
        "group": "write",
        "risk": "write",
        "summary": "编辑帖子",
        "params": ["feed_id", "guild_id", "channel_id", "create_time", "feed_type", "title", "content", "markdown_content", "content_file", "file_paths", "video_paths", "at_users", "urls", "topic_names", "clear_images", "clear_videos"],
        "required": ["feed_id", "guild_id", "channel_id", "create_time"],
    },
    {
        "name": "feed.top-feed",
        "domain": "feed",
        "action": "top-feed",
        "group": "write",
        "risk": "write",
        "summary": "帖子置顶/取消置顶",
        "params": ["feed_id", "user_id", "create_time", "guild_id", "action", "top_type"],
        "required": ["feed_id", "user_id", "create_time", "guild_id"],
    },
    {
        "name": "feed.set-feed-essence",
        "domain": "feed",
        "action": "set-feed-essence",
        "group": "write",
        "risk": "write",
        "summary": "设置/取消精华",
        "params": ["feed_id", "action"],
        "required": ["feed_id"],
    },
    {
        "name": "feed.push-essence-feed",
        "domain": "feed",
        "action": "push-essence-feed",
        "group": "write",
        "risk": "write",
        "summary": "推送精华帖通知",
        "params": ["feed_id"],
        "required": ["feed_id"],
    },
    {
        "name": "feed.move-feed",
        "domain": "feed",
        "action": "move-feed",
        "group": "write",
        "risk": "write",
        "summary": "移动帖子到其他版块",
        "params": ["guild_id", "channel_id", "original_channel_id", "feed_id"],
        "required": ["guild_id", "channel_id", "original_channel_id", "feed_id"],
    },
    {
        "name": "feed.quick-publish",
        "domain": "feed",
        "action": "quick-publish",
        "group": "shortcut",
        "risk": "",
        "summary": "选择频道和版块，一键发帖",
        "params": ["content", "markdown_content", "title", "content_file", "feed_type", "file_paths", "video_paths", "at_users", "urls", "topic_names", "resume_id", "pick"],
        "required": [],
    },
    {
        "name": "feed.search-and-comment",
        "domain": "feed",
        "action": "search-and-comment",
        "group": "shortcut",
        "risk": "",
        "summary": "搜索帖子并评论",
        "params": ["guild_id", "query", "content", "resume_id", "pick"],
        "required": ["guild_id", "query", "content"],
    },
    {
        "name": "feed.delete-and-mute",
        "domain": "feed",
        "action": "delete-and-mute",
        "group": "shortcut",
        "risk": "high-risk-write",
        "summary": "搜帖删帖并禁言",
        "params": ["guild_id", "query", "resume_id", "pick", "set", "time_stamp"],
        "required": ["guild_id", "query"],
    },
    {
        "name": "feed.latest-feeds-detail",
        "domain": "feed",
        "action": "latest-feeds-detail",
        "group": "shortcut",
        "risk": "",
        "summary": "获取频道最新帖子详情",
        "params": ["count", "resume_id", "pick"],
        "required": [],
    },
    {
        "name": "feed.hot-feeds-detail",
        "domain": "feed",
        "action": "hot-feeds-detail",
        "group": "shortcut",
        "risk": "",
        "summary": "获取频道热门帖子详情",
        "params": ["count", "resume_id", "pick"],
        "required": [],
    },
    {
        "name": "manage.get-guild-info",
        "domain": "manage",
        "action": "get-guild-info",
        "group": "query",
        "risk": "read",
        "summary": "查看腾讯频道资料",
        "params": ["guild_id"],
        "required": ["guild_id"],
    },
    {
        "name": "manage.get-my-join-guild-info",
        "domain": "manage",
        "action": "get-my-join-guild-info",
        "group": "query",
        "risk": "read",
        "summary": "查看我的腾讯频道列表",
        "params": [],
        "required": [],
    },
    {
        "name": "manage.get-user-info",
        "domain": "manage",
        "action": "get-user-info",
        "group": "query",
        "risk": "read",
        "summary": "查看用户资料",
        "params": ["guild_id", "tiny_id"],
        "required": [],
    },
    {
        "name": "manage.get-guild-member-list",
        "domain": "manage",
        "action": "get-guild-member-list",
        "group": "query",
        "risk": "read",
        "summary": "查看成员列表（分页）",
        "params": ["guild_id", "next_page_token"],
        "required": ["guild_id"],
    },
    {
        "name": "manage.guild-member-search",
        "domain": "manage",
        "action": "guild-member-search",
        "group": "query",
        "risk": "read",
        "summary": "按昵称搜索成员",
        "params": ["guild_id", "keyword", "num", "next_pos"],
        "required": ["guild_id", "keyword"],
    },
    {
        "name": "manage.get-guild-channel-list",
        "domain": "manage",
        "action": "get-guild-channel-list",
        "group": "query",
        "risk": "read",
        "summary": "查看版块列表",
        "params": ["guild_id"],
        "required": ["guild_id"],
    },
    {
        "name": "manage.search-guild-content",
        "domain": "manage",
        "action": "search-guild-content",
        "group": "query",
        "risk": "read",
        "summary": "搜索腾讯频道/帖子/作者",
        "params": ["keyword", "scope", "next_page_token"],
        "required": ["keyword"],
    },
    {
        "name": "manage.get-join-guild-setting",
        "domain": "manage",
        "action": "get-join-guild-setting",
        "group": "query",
        "risk": "read",
        "summary": "查看腾讯频道加入设置",
        "params": ["guild_id"],
        "required": ["guild_id"],
    },
    {
        "name": "manage.get-guild-share-url",
        "domain": "manage",
        "action": "get-guild-share-url",
        "group": "query",
        "risk": "read",
        "summary": "获取腾讯频道分享短链",
        "params": ["guild_id"],
        "required": ["guild_id"],
    },
    {
        "name": "manage.get-share-info",
        "domain": "manage",
        "action": "get-share-info",
        "group": "query",
        "risk": "read",
        "summary": "查看分享链接信息",
        "params": ["url"],
        "required": ["url"],
    },
    {
        "name": "manage.kick-guild-member",
        "domain": "manage",
        "action": "kick-guild-member",
        "group": "write",
        "risk": "high-risk-write",
        "summary": "踢出成员",
        "params": ["guild_id", "tiny_id", "member_tinyids", "blacklist", "revoke_msgs"],
        "required": ["guild_id"],
    },
    {
        "name": "manage.modify-member-shut-up",
        "domain": "manage",
        "action": "modify-member-shut-up",
        "group": "write",
        "risk": "write",
        "summary": "禁言/解禁成员",
        "params": ["guild_id", "tiny_id", "time_stamp"],
        "required": ["guild_id", "tiny_id"],
    },
    {
        "name": "manage.update-guild-info",
        "domain": "manage",
        "action": "update-guild-info",
        "group": "write",
        "risk": "write",
        "summary": "修改腾讯频道名称/简介",
        "params": ["guild_id", "guild_name", "guild_profile"],
        "required": ["guild_id"],
    },
    {
        "name": "manage.modify-guild-number",
        "domain": "manage",
        "action": "modify-guild-number",
        "group": "write",
        "risk": "write",
        "summary": "修改腾讯频道号",
        "params": ["guild_id", "guild_number"],
        "required": ["guild_id", "guild_number"],
    },
    {
        "name": "manage.create-guild-role-group",
        "domain": "manage",
        "action": "create-guild-role-group",
        "group": "write",
        "risk": "write",
        "summary": "创建身份组",
        "params": ["guild_id", "name"],
        "required": ["guild_id", "name"],
    },
    {
        "name": "manage.modify-guild-role-group",
        "domain": "manage",
        "action": "modify-guild-role-group",
        "group": "write",
        "risk": "write",
        "summary": "修改身份组",
        "params": ["guild_id", "role_id", "name"],
        "required": ["guild_id", "role_id", "name"],
    },
    {
        "name": "manage.add-role-members",
        "domain": "manage",
        "action": "add-role-members",
        "group": "write",
        "risk": "write",
        "summary": "向身份组添加成员",
        "params": ["guild_id", "role_id", "tiny_ids"],
        "required": ["guild_id", "role_id", "tiny_ids"],
    },
    {
        "name": "manage.remove-role-members",
        "domain": "manage",
        "action": "remove-role-members",
        "group": "write",
        "risk": "high-risk-write",
        "summary": "从身份组移除成员",
        "params": ["guild_id", "role_id", "tiny_ids"],
        "required": ["guild_id", "role_id", "tiny_ids"],
    },
    {
        "name": "manage.join-guild",
        "domain": "manage",
        "action": "join-guild",
        "group": "write",
        "risk": "write",
        "summary": "加入腾讯频道",
        "params": ["guild_id"],
        "required": ["guild_id"],
    },
    {
        "name": "manage.create-channel",
        "domain": "manage",
        "action": "create-channel",
        "group": "write",
        "risk": "write",
        "summary": "创建子版块",
        "params": ["guild_id", "channel_name"],
        "required": ["guild_id", "channel_name"],
    },
    {
        "name": "manage.delete-channel",
        "domain": "manage",
        "action": "delete-channel",
        "group": "write",
        "risk": "high-risk-write",
        "summary": "删除版块",
        "params": ["guild_id", "channel_ids"],
        "required": ["guild_id", "channel_ids"],
    },
    {
        "name": "manage.modify-channel",
        "domain": "manage",
        "action": "modify-channel",
        "group": "write",
        "risk": "write",
        "summary": "修改版块名称",
        "params": ["guild_id", "channel_id", "channel_name"],
        "required": ["guild_id", "channel_id", "channel_name"],
    },
    {
        "name": "manage.upload-guild-avatar",
        "domain": "manage",
        "action": "upload-guild-avatar",
        "group": "write",
        "risk": "write",
        "summary": "修改腾讯频道头像",
        "params": ["guild_id", "image_path"],
        "required": ["guild_id", "image_path"],
    },
    {
        "name": "manage.create-theme-private-guild",
        "domain": "manage",
        "action": "create-theme-private-guild",
        "group": "write",
        "risk": "write",
        "summary": "创建频道(公开/私密)",
        "params": ["image_path", "theme", "guild_name", "guild_profile", "community_type"],
        "required": ["image_path"],
    },
    {
        "name": "manage.add-admin",
        "domain": "manage",
        "action": "add-admin",
        "group": "write",
        "risk": "write",
        "summary": "设置超级管理员",
        "params": ["guild_id", "tiny_ids"],
        "required": ["guild_id", "tiny_ids"],
    },
    {
        "name": "manage.remove-admin",
        "domain": "manage",
        "action": "remove-admin",
        "group": "write",
        "risk": "high-risk-write",
        "summary": "移除超级管理员",
        "params": ["guild_id", "tiny_ids"],
        "required": ["guild_id", "tiny_ids"],
    },
    {
        "name": "manage.push-group-dm-msg",
        "domain": "manage",
        "action": "push-group-dm-msg",
        "group": "write",
        "risk": "write",
        "summary": "向目标用户发送频道私信信息",
        "params": ["peer_tiny_id", "source_guild_id", "text", "ref"],
        "required": ["text"],
    },
    {
        "name": "manage.update-join-guild-setting",
        "domain": "manage",
        "action": "update-join-guild-setting",
        "group": "write",
        "risk": "write",
        "summary": "修改腾讯频道加入设置",
        "params": ["guild_id", "join_type"],
        "required": ["guild_id", "join_type"],
    },
    {
        "name": "manage.leave-guild",
        "domain": "manage",
        "action": "leave-guild",
        "group": "write",
        "risk": "high-risk-write",
        "summary": "退出腾讯频道",
        "params": ["guild_id"],
        "required": ["guild_id"],
    },
    {
        "name": "manage.notices-on",
        "domain": "manage",
        "action": "notices-on",
        "group": "write",
        "risk": "write",
        "summary": "开启频道消息通知（有新互动时自动推送）",
        "params": ["session_key", "confirm"],
        "required": [],
    },
    {
        "name": "manage.notices-off",
        "domain": "manage",
        "action": "notices-off",
        "group": "write",
        "risk": "write",
        "summary": "关闭频道消息通知",
        "params": ["session_key"],
        "required": [],
    },
    {
        "name": "manage.notices-status",
        "domain": "manage",
        "action": "notices-status",
        "group": "query",
        "risk": "read",
        "summary": "查看频道消息通知状态",
        "params": [],
        "required": [],
    },
    {
        "name": "manage.check-notices",
        "domain": "manage",
        "action": "check-notices",
        "group": "query",
        "risk": "read",
        "summary": "检查新的频道通知（增量）",
        "params": [],
        "required": [],
    },
    {
        "name": "manage.subscribe-notices",
        "domain": "manage",
        "action": "subscribe-notices",
        "group": "write",
        "risk": "write",
        "summary": "开启频道消息通知",
        "params": [],
        "required": [],
    },
    {
        "name": "manage.unsubscribe-notices",
        "domain": "manage",
        "action": "unsubscribe-notices",
        "group": "write",
        "risk": "write",
        "summary": "关闭频道消息通知",
        "params": [],
        "required": [],
    },
    {
        "name": "manage.check-new-notices",
        "domain": "manage",
        "action": "check-new-notices",
        "group": "query",
        "risk": "read",
        "summary": "检查新的频道通知",
        "params": [],
        "required": [],
    },
    {
        "name": "manage.get-recent-notices",
        "domain": "manage",
        "action": "get-recent-notices",
        "group": "query",
        "risk": "read",
        "summary": "获取最近的通知记录（本地）",
        "params": [],
        "required": [],
    },
    {
        "name": "manage.deal-notice",
        "domain": "manage",
        "action": "deal-notice",
        "group": "write",
        "risk": "write",
        "summary": "处理系统通知（如同意/拒绝加入申请）",
        "params": ["notice_id", "action_id", "ref"],
        "required": ["action_id"],
    },
    {
        "name": "manage.notify-daemon",
        "domain": "manage",
        "action": "notify-daemon",
        "group": "write",
        "risk": "write",
        "summary": "启动后台通知检查服务",
        "params": ["push_command", "interval", "once", "__worker__"],
        "required": [],
    },
    {
        "name": "manage.search-and-join",
        "domain": "manage",
        "action": "search-and-join",
        "group": "shortcut",
        "risk": "",
        "summary": "搜索频道并加入",
        "params": ["keyword", "resume_id", "pick"],
        "required": ["keyword"],
    },
    {
        "name": "cli.version",
        "domain": "cli",
        "action": "version",
        "group": "read",
        "risk": "read",
        "summary": "查看 tencent-channel-cli 版本",
        "params": [],
        "required": [],
    },
    {
        "name": "cli.doctor",
        "domain": "cli",
        "action": "doctor",
        "group": "read",
        "risk": "read",
        "summary": "CLI 自检（版本/系统密钥链/登录状态/服务端点/业务探测）",
        "params": [],
        "required": [],
    },
)
